- src/components/Footer.astro
- src/components/Socials.astro
- src/pages/index.astro
As the title says, the div/map block of code which renders social media was duplicated on `index.astro` and `Footer.astro`, so I made a new component for it
> Add `Socials` component to avoid code duplication

- src/contents/dynamic-og-images.md
> Fix typo in dynamic-og-images.md

- .eslintignore
- .eslintrc.js
- .prettierignore
- package-lock.json
- package.json
- src/components/Header.astro
> Add ESLint

- README.md
> Mention ESLint in the readme

- src/utils/getPostsByTag.ts
- src/utils/slugify.ts
@satnaing Thanks for this awesome template, I've been reading through the source and learning a lot!
I found a typo as I was reading and thought I would help out. Cheers!
> fix: slugifyAll typo

- .eslintignore
- .gitignore
Added yarn files and directories to gitignore and eslintignore.
> fix(ignore): added yarn directories to ignorefiles

- src/layouts/Layout.astro
It will help improve the SEO score of websites.
P.S. - It is also a good idea to add it to the robots.txt, but we can't use relative paths there.
> Adding Sitemap to the Layout

- src/content/_schemas.ts
- src/content/blog/adding-new-post.md
- src/layouts/Layout.astro
- src/layouts/PostDetails.astro
> [Feature] Add support for canonical urls

- astro.config.mjs
Fixed tailwind base styles config that changed since @astrojs/tailwind-4.0 
Source:
https://github.com/withastro/astro/blob/main/packages/integrations/tailwind/CHANGELOG.md#400
> Fixed tailwind base styles

- src/styles/base.css
> fix: anchor overflow on small screen size

- src/components/Breadcrumbs.astro
> decodeURIComponent unicode tag chars in breadcrumb

- src/content/blog/setting-dates-via-git-hooks.md
After the comments on #207 I wrote it as a post instead. 
Answers #199.
Also posted on my blog: https://smale.codes/posts/setting-dates-via-git-hooks/
> feat: adds post on git hook date setting

- src/assets/socialIcons.ts
- src/types.ts
- remove SocialMedia type from src/types.ts
- generate each social icon type from socialIcons object instead
> refactor: remove SocialObjects type and update SocialObjects type

- src/styles/base.css
As I said in #229. Just a tiny style fix.
It also closes #229.
> fix: resolve broken line break in inline code

- README.md
Add the pnpm install command to README.md.
> docs: use pnpm install

- astro.config.ts
- package-lock.json
- package.json
- src/styles/base.css
Update Astro and its related dependencies. Support light/dark themes in code blocks.
https://github.com/user-attachments/assets/331c9980-864b-41ed-92ff-b21a59b74953
> feat: support light/dark theme in code blocks

- .husky/pre-commit
- README.md
- package-lock.json
- package.json
Including pre-commit hook and its related dependencies in this template creates unnecessary confusion. 
Moreover, users can configure their desired CI/CD and git hook if needed.
> build: remove pre-commit git hook

- .gitignore
- package-lock.json
- package.json
Remove post-processing static site optimizer_ Jampack due to insignificant differences in build output and unmet peer dependency issues.
Closes #212, resolves #277
> build: remove jampack

- README.md
> docs: add warning for `yarn 1` & `sharp`

- .github/workflows/ci.yml
Add a continuous integration workflow to check linting, code formatting, and ensure successful builds.
> ci: add CI workflow

- src/content/blog/how-to-add-an-estimated-reading-time.md
> docs: update estimated reading time blog post

- astro.config.ts
- package-lock.json
- package.json
- src/content/config.ts
- Bump Astro from v4.13 to v4.14.2
- use experimental Content Layer API.
> AstroPaper v4.4.0

- src/components/Datetime.tsx
> feat: Add pencil icon before suggestion changes text

- .gitignore
- package.json
- pnpm-lock.yaml
- src/layouts/PostDetails.astro
- src/pages/search.astro
- tsconfig.json
Replace React with pagefind for static site search
> feat: add pagefind search

- src/data/blog/how-to-add-latex-equations-in-blog-posts.md
Update LaTeX equations guide for AstroPaper v5
#412
> docs: update LaTeX equations guide in Astro blog posts

- src/data/blog/how-to-integrate-giscus-comments.md
The current doc says to add constant into the `config.ts`, But since version 5, we are locating in `constants.ts`
Issues: #467
> Update how-to-integrate-giscus-comments.md to set constants in right file

- docker-compose.yml
> Update docker-compose.yml to use latest lts version like Dockerfile

- src/components/Header.astro
> fix: adjust nav bar alignment in heading

- astro.config.ts
- package.json
- pnpm-lock.yaml
Upgrades Astro to v5.9.0 and adjusts `astro.config.ts` accordingly.
I just used the template and wanted to use the latest Astro version.
- Change in `image.experimentalLayout` according to https://github.com/withastro/astro/blob/main/packages/astro/CHANGELOG.md#upgrading
- Change to `experimental.svg` according to https://github.com/withastro/astro/blob/main/packages/astro/CHANGELOG.md#minor-changes-2
After looking at some issues here, this should fix: #519 and fix: #514
Closes: #519 
Closes: #514
> build(deps): upgrade astro and related packages

- src/components/BackToTopButton.astro
- src/components/Tag.astro
- src/layouts/PostDetails.astro
- src/styles/typography.css
Update TailwindCSS typography overrides to use less `important`; and update selectors to make them easier to read.
> refactor: update tailwind typography css overrides

- astro.config.ts
- package.json
- pnpm-lock.yaml
- bump astro from 5.9.2 to 5.10.0
- upgrade minor and patch dependencies
> build(deps): upgrade astro and dependencies

- src/components/EditPost.astro
- src/config.ts
Suggest Changes => Edit page
Also, updated the styling to be more consistent.
> fix: update edit post link styling and text

- README.md
Successfully built site with bun.
Closes: #
> docs: add Bun installation instructions to README

- src/layouts/PostDetails.astro
Just a small change that bothered me: The vertical bar should be hidden when the global `editPost.enabled` is `false`
Enabled
Disabled
Fixed
none
none
Closes:  none
> fix: make post header vertical bar respect global settings
