satnaing/astro-paper

src/pages/index.astro
src/pages/posts/[slug].astro
src/pages/posts/index.astro
src/pages/rss.xml.ts
src/pages/search.astro
src/pages/tags/[tag].astro
src/pages/tags/index.astro

This PR changes the glob patterns used to find `.md` files,  by doing this, you can still have:
```
contents
├── post1.md
└── post2.md
```
But can also add subfolders to have your files sorted in a better way, eg:
```
contents
├── post1.md
├── post2.md
├── folder1
│     └── post3.md
└── folder2
└── folder3
└── post4.md
```

Change glob

---

src/components/Search.tsx

When there no results for a query, it should say 0 ***results*** not 0 ***result***. This PR fixes this problem.

fix: should be 0 results not result

---

src/content/_schemas.ts

https://zod.dev/?id=strict
If schema(s) are made with strict, it will disallow extra keys in the markdown frontmatter.

Disallow unknown keys with .strict()

---

package.json

Using pnpm as package manager, when commit an Astro template, prettier throw the error 'No parser could be inferred for file: ...'.
To reproduce you can create a new branch, install the packages with `pnpm install`, modify an Astro template (ex. src/pages/index.astro) and try to commit.
Adding the parameter `--plugin-search-dir=.` to prettier command in `lint-staged` section of `package.json` solved the problem for me. I found the solution in this [comment](https://github.com/withastro/prettier-plugin-astro/issues/97#issuecomment-1013645333) for more details.

(lint-staged) Fix prettier error 'No parser could be inferred for file' using pnpm

---

astro.config.mjs
package-lock.json
package.json
src/layouts/Layout.astro
src/layouts/PostDetails.astro
src/utils/generateOgImage.tsx

Convert social images from SVG format to PNG format to avoid SVG limitation, especially in Twitter social cards.
This PR will close #40

Convert social images from SVG to PNG format

---

package.json
tsconfig.json

Hello, 
from issue #48 . I have the same issue after updating astro to 2.1.4
and I have fixed it by updating the tsconfig file
It seems like the new astro@2.1.4 was trying to call react from the wrong path.

fix: build error astro@2.1.4 && update astro@2.1.5

---

src/components/Datetime.tsx
src/config.ts
src/content/blog/how-to-configure-astropaper-theme.md

This PR just adds a simple setting to control date format at build- and run-time. You can even set it to `[]` to refer to system(s) environment. IMHO, it can be a good idea to control locale settings in a centralized fashion for being consistent.

Add locale configuration

---

src/layouts/PostDetails.astro

Hello,
unslugified tags in post detail page seem to cause some problems:
1. Inconsistent display of the same tag on different pages.
2. Direct to a 404 page from an existing tag.
I have fixed it by modifying the frontmatter of `PostDetails.astro`.

Fix: slugify tags in post detail page

---

tailwind.config.cjs

- Fixes tailwind config's JSDOC placement. Without this change IDE intellisense does not work. 
Broken in 02d29f09144db026db8cf26f424e3ca66f0cd225

fix: tailwind jsdoc for intellisense

---

src/components/Search.tsx

Memoising the value of `fuse` based off of the search list to prevent reinstantiating it on search keypress.
`searchList` will never change, so this will reduce work needed to do while searching big post lists.

Stop reinstantiating Fuse on keypress

---

src/utils/getUniqueTags.ts

Previously, the `forEach` loop was spreading the tags list and updating it on every iteration. So for every post, the slugify operation was happening on previously converted data again.
Similarly, the last filter operation to remove duplicates was repeated for every post ($`O(n\log{}n)`$) instead of checking once at the end ($`O(n)`$).
Additional suggestion: Removing duplicates can be better handled by using [`lodash.uniq`](https://lodash.com/docs/3.10.1#uniq) or [`Set`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set)

Refactor: getUniqueTags should perform conversions exactly once per tag

---

astro.config.mjs
src/content/blog/how-to-configure-astropaper-theme.md

Using SITE.website in astro.config.mjs causes the problem . Thus, change back to the original url string in site value of .
Closes: #72

fix: replace SITE.website with a URL in astro.config site value

---

public/robots.txt
src/pages/robots.txt.ts

Adds sitemap URL to robots.txt, This way it follows the guidelines given by both astro-sitemap [docs](https://docs.astro.build/en/guides/integrations-guide/sitemap/#usage) and google recommendation.

feat: dynamically generate robots.txt

---

src/styles/base.css
tailwind.config.cjs

fix #162 
Seems like the style has been fixed and there is no breaking change.

fix: pre > code font color

---

README.md
docker-compose.yml

- Add `docker-compose.yml` file
- Add docker commands into the README.md file
Close #172

feat: Add docker-compose file

---

src/layouts/PostDetails.astro
src/styles/base.css

Implement back-to-top button under tags in PostDetails page. Update html scroll-behavior to smooth.
Closes: #156

feat: implement back-to-top button in blog post page

---

src/components/Tag.astro
src/layouts/PostDetails.astro
src/pages/tags/[tag].astro
src/pages/tags/index.astro
src/utils/getUniqueTags.ts

Update slugified titles to be unslugified. This is for better SEO and better a11y. Url and tag elelemnts will still be slugified.
Closes: #179

feat: replace slugified title with unslugified tag name

---

src/components/Datetime.tsx
src/layouts/Layout.astro

Update modDatetime props type to have null type for components that have modDatetime as props.

fix: solve modDatetime type errors

---

src/content/blog/how-to-add-a-new-social-icon.md

Follwoing on from the comment https://github.com/satnaing/astro-paper/pull/216#issuecomment-1880664828, this post captures the how to of adding your own Icons

feat: adds blog post for how to add a social icon

---

src/components/Header.astro

This removes the extra "right-padding" inside the header search icon when `lightAndDarkMode` is `false` so UI is consistent.

fix: include <li> block inside if statement

---

src/layouts/PostDetails.astro

Implemented easy links to headings (h2-h6) on post details.
The links are aria-hidden and only show on hover.
I was going to set this up for my own blog so I thought I'd share in case you want to include this in Astro Paper.

feat: add heading links to PostDetails

---

src/config.ts
src/content/blog/how-to-configure-astropaper-theme.md
src/pages/search.astro
src/types.ts
src/utils/getSortedPosts.ts
src/utils/getUniqueTags.ts
src/utils/postFilter.ts

If the pubDateTime is not reached:
- Post is not not shown in the index
- Post's tags are not shown in the tags page
- Post can't be found in search
The scheduledPost are visible 15 minutes before pubDateTime by default, to let the time to rebuild the website. It can be set as a config `SITE` variable: `scheduledPostMargin`
Fix #233

feat: hide posts when PubDateTime is not reached

---

src/styles/base.css

The result is better on images with caption defined as: 
```
*caption*
```

fix: disable margin bottom on image

---

src/pages/index.astro

Changes made:
- Removed the recent posts section if there is no post under the recent section.
- Eliminated unnecessary <Hr /> tags when there are no recent posts.
- Extracted all-links from the recent section.
Closes: #204

fix: remove recent posts section if there's no post

---

src/layouts/PostDetails.astro

**_Description_**
Update back button in PostDetails.astro to redirect to home page when there's no route history.
If a blog post url is pasted in the browser and there's no route history, prior to this commit, back button did not work as expected. Now, if there's somewhere to go back, the back button will go back to the previous route.
If not, the back button will redirect to home page.
**_Before_**
https://github.com/satnaing/astro-paper/assets/53733092/a4bfa96d-4d4b-4c39-b827-ce8072a0e1f5
**_After_**
https://github.com/satnaing/astro-paper/assets/53733092/098f6c0b-7e9b-4bd1-b032-92444063d9df
**_Tested Browsers_**
- Chrome ✅ (mobile/desktop)
- Safari ✅ (mobile/desktop)
- Opera ✅ (mobile/desktop)
- Firefox ✅
- Edge ✅

fix: update back button to redirect to home when no route history

---

src/content/blog/predefined-color-schemes.md

Seems to be missed whilst copy pasting the sentence. `Light` -> `Dark`

Fix a small typo in predefined-color-schemes.md

---

src/components/Breadcrumbs.astro
src/components/Header.astro
src/components/Search.tsx
src/components/Tag.astro
src/layouts/Posts.astro
src/layouts/TagPosts.astro
src/pages/index.astro
src/pages/rss.xml.ts

Both the canonical and RSS article URLs end with "/", for consistency with the standard, it is best to use "/" at the end of the article URL. 
Otherwise, there will be an additional 308 redirect.

feat: all posts link end with /

---

src/layouts/PostDetails.astro

Yeah, what you see is true. In the previous versions, the SITE.title was NOT added to the Post Title.
I fixed this issue in this PR.

feat: add SITE.title in Post Title

---

src/layouts/PostDetails.astro

Implement scroll indicator in `PostDetails` page.
https://github.com/satnaing/astro-paper/assets/53733092/c18c627f-9643-4de9-8f7f-b64609d16188

feat: add scroll indicator in blog posts

---

src/components/Datetime.tsx

Hello, I usually create a new post with FrontMatterCMS (vscode plugin) which creates both pubDateTime and modDateTime at the same time in a new post.
Then I noticed that. When the time of both parts is the same. The page will show the word "Update". I would like to change this to show the word "Update" only if modDateTime is more current than pubDateTime.
Thank you for creating this theme. Hopefully, this small change will be beneficial to you.

refactor: Display "Update:" only if modDateTime more current than pubDateTime

---

.vscode/astro-paper.code-snippets

Add `$CURRENT_TIMEZONE_OFFSET` in vscode code snippets to reflect real time.
VSCode docs: https://code.visualstudio.com/docs/editor/userdefinedsnippets#_variables

Add timezone offset in custom code snippets

---

src/config.ts
src/layouts/Layout.astro
src/types.ts

- Add author profile URL to `SITE` variables
- Add JSON-LD to `Layout.astro`
- If no `modDatetime`, not used
After that, posts page are valid with Google test tool:
https://search.google.com/test/rich-results
Google recommandations about JSON-LD Structured data:
https://developers.google.com/search/docs/appearance/structured-data/article#json-ld

feat: add JSON-LD structured data

---

src/components/Datetime.tsx
src/components/LinkButton.astro

Avoid `undefined` when passing `className` as a prop, and trimming will remove any extra spacing.

fix: avoid `undefined` when passing class-name as prop

---

.eslintrc.js

Adding `parser: "@typescript-eslint/parser"` as the default parser allows ESLint to lint `*.(ts|tsx)` files.
I am adding an unused variable in `src/config.ts` leads to the expectation of receiving an error from the  [no-unused-vars](https://eslint.org/docs/latest/rules/no-unused-vars) rule in the output. However, ESLint fails to recognize the `import type` syntax.
```ts
import type { Site, SocialObjects } from "./types";
const foo = ""; // <-- unused variable
// skip
```
improving DX in VS Code with the ESLint extension for better error detection.

chore: use `@typescript-eslint/parser` as the default parser

---

src/components/Pagination.astro

Avoid creating unnecessary `-svg` class-name in the pagination component

refactor: avoid using unnecessary class-name in the pagination component

---

src/layouts/PostDetails.astro

- Making the heading links focusable for navigation using a keyboard's tab button.
- Keeping the anchor link in the accessibility tree while hiding the "#" symbol for the screen reader.
https://github.com/satnaing/astro-paper/assets/26923823/ef062564-8f9f-48ab-99d0-e881a599dd42

feat: keyboard focusable heading links

---

tailwind.config.cjs

I had a similar issue using the `dark:` prefix. Ended up fixing it by adding the `darkMode` selector to the tailwind config. https://tailwindcss.com/docs/dark-mode
Fixes #288 
PS @satnaing, love this template!

fix: adding data-theme to tailwind config

---

src/layouts/PostDetails.astro

The `<article>` tag already has an implicit role defined by the HTML specification, so we do not need to add an ARIA role attribute.
Reference:
- https://html-validate.org/rules/no-redundant-role.html
- https://web.dev/learn/accessibility/aria-html#aria_in_html
After the change:

refactor: remove redundant role

---

tsconfig.json

Trailing comma is invalid json syntax. This makes some tools like `vim` breaks while opening this project.
https://github.com/vim/vim/blob/22105fd1fe0dcfe993b5c04c6ebe017a626116e3/runtime/ftplugin/astro.vim#L45-L61

fix: invalid json syntax in `tsconfig.json`

---

src/content/blog/how-to-integrate-giscus-comments.md

Giscus enables dynamic user comments on static sites hosted on Github pages. This post gives an outline on how to integrate Giscus with AstroPaper.
resolves #250

docs: add guide on integrating user comments with Giscus

---

package-lock.json
src/content/blog/dynamic-og-images.md
src/utils/generateOgImages.tsx
src/utils/loadGoogleFont.ts
src/utils/og-templates/post.tsx
src/utils/og-templates/site.tsx

| before | after |
| :----: | :---:| 
| ![before_jp](https://github.com/satnaing/astro-paper/assets/53370227/578589fa-deb6-44a9-9799-45653f61c1ba) | ![after_jp](https://github.com/satnaing/astro-paper/assets/53370227/9d444425-f15e-4e69-8221-8815f5e60c54) |
| ![before_cn](https://github.com/satnaing/astro-paper/assets/53370227/2ff4dbc4-16e9-46f1-adc1-045c19ec06f2) | ![after_cn](https://github.com/satnaing/astro-paper/assets/53370227/12a909f5-05df-4d43-adcb-5d8d90d0ee78) |
if you want more language support you can add it on your own
```js
const fontsConfig = [
{ name: "Noto Sans JP", font: "Noto+Sans+JP", weight: 400, style: "normal", },
{ name: "Noto Sans JP", font: "Noto+Sans+JP:wght@700", weight: 700, style: "normal", }, 
{ name: "Noto Sans", font: "Noto+Sans", weight: 400, style: …
```

fix: resolve issue with non-Latin characters not displaying correctly on OG images using Google Fonts API

---

src/content/blog/setting-dates-via-git-hooks.md

Add a section about the removal of the pre-commit
hook in v4.3.0.

docs: update pre-commit hook blog post

---

src/components/Search.tsx
src/styles/base.css

Main changes are for background and border opacity syntax:
- from `border-opacity-*` to `border-[color]/[opacity]`
- from `bg-opacity-*` to `bg-[color]/[opacity]`

refactor: update tailwind classes to v3 syntax

---

src/components/LinkButton.astro
src/pages/404.astro

Remove aria-label from `<h1>` of 404 page and disabled LinkButton.
Resolves #263

fix(a11y): remove aria-labels from non-interactive elements

---

README.md

docs: add instructions for Google Site Verification in AstroPaper

---

src/content/blog/how-to-add-an-estimated-reading-time.md

i find inside `search.astro` also use `getSortedPosts`, and there is duplicated item on the list, i though that the duplicated one was supposed to be `search.astro`

fix(blog): correct file reference in reading time guide

---

package-lock.json

https://www.cve.org/CVERecord?id=CVE-2024-4067
> The NPM package `micromatch` prior to 4.0.8 is vulnerable to Regular Expression Denial of Service (ReDoS). The vulnerability occurs in `micromatch.braces()` in `index.js` because the pattern `.*` will greedily match anything. By passing a malicious payload, the pattern matching will keep backtracking to the input while it doesn't find the closing bracket. As the input size increases, the consumption time will also increase until it causes the application to hang or slow down. There was a merged fix but further testing shows the issue persists. This issue should be mitigated by using a safe pattern that won't start backtracking the regular expression due to greedy matching. This issue was fixed in version 4.0.8.

vulnerability found in micromatch. bump version to 4.0.8

---

src/utils/og-templates/site.tsx

Fix the issue where SITE.website cannot be rendered due to missing some font characters

fix(og): add the missing SITE.website to loadGoogleFonts 

---

src/content/blog/how-to-add-latex-equations-in-blog-posts.md
src/content/blog/latex-rendering.md

This PR introduces LaTeX equation rendering capability to AstroPaper, enhancing its functionality for technical and scientific writing. By integrating KaTeX, we now support rendering of both inline and block LaTeX equations in Markdown files.
I do think this will enlarge the use of AstroPaper in the scientific community. 
Many technical bloggers and documentation writers need to include mathematical equations in their content. Adding LaTeX support significantly expands AstroPaper's usefulness for these users, making it a more versatile platform for a wider range of creators.
- Updated `astro.config.mjs` to include `remark-math` and `rehype-katex` plugins.
- Modified the `Layout.astro` file to include KaTeX CSS.
- Added necessary dependencies (`rehype-katex`, `remark-math`, and `katex`) to …

Render LaTeX

---

src/layouts/PostDetails.astro
src/pages/posts/[slug]/index.astro

Add `Prev Post` and `Next Post` links at the bottom of a blog post.
Resolves #358

feat: add prev/next links at the bottom of blog post

---

src/layouts/Layout.astro

Improve page performance by preloading the font with `as="style"` and loading the theme script asynchronously.

perf: preload font and load theme script asynchronously

---

src/pages/posts/[...page].astro
src/pages/posts/[page].astro

I recently followed the v4.4.0 -> v4.5.0 update and noticed the out of order posts. This adds the date sorted posts back like they were in v4.4.0.

Fix post sorting on /posts/

---

docker-compose.yml
src/content/blog/how-to-integrate-giscus-comments.md

- Fixed giscus blog post
- Change the docker-compose.yaml to latest node version (20)

Fix giscus blog post

---

src/components/Datetime.tsx
src/config.ts
src/content/blog/how-to-configure-astropaper-theme.md
src/content/config.ts
src/layouts/PostDetails.astro
src/types.ts

This PR implements the feature "edit page" by referring to the implementation of [Hugo PaperMod](https://github.com/adityatelange/hugo-PaperMod/blob/master/layouts/partials/edit_post.html)
close: #191

feat: add edit post feature

---

.github/CODE_OF_CONDUCT.md
.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE/✨-feature-request.md
.github/ISSUE_TEMPLATE/🐞-bug-report.md
.github/ISSUE_TEMPLATE/📝-documentation-improvement.md

Apply Prettier formatting to markdown files under `.github/` directory.
Closes: #

chore: format .github markdown files with Prettier

---

src/components/Header.astro
src/config.ts
src/content/blog/how-to-configure-astropaper-theme.md
src/pages/archives/index.astro
src/types.ts
src/utils/getPostsByGroupCondition.ts
tailwind.config.cjs

This PR implements the archives menu with a SITE config to control whether to show it.
The new page "archives" groups the posts by its publish year then month and demonstrate all the posts archived like below
close: #361

feat: add archives page with configurable menu

---

src/assets/socialIcons.ts
src/components/ShareLinks.astro
src/config.ts

Replacing the `old twitter` icon and share link to `X`
As the twitter was changed to `X`, I guess we could replace it!
It won't  crash the page, But who uses twitter, it wont appear ... he needs to switch to `X`
Is it considered a Break change?
it will be like this

Replace Twitter to X

---

src/content/blog/how-to-add-an-estimated-reading-time.md

Update the blog post "adding estimated Reading Time".
Closes: #406

docs: update est readingTime blog post

---

src/components/Search.tsx

Focus on text input when search bar is displayed
Focus on search input to avoid unnecessary click / focus change.

Update Search.tsx :  focus on search bar displayed

---

src/pages/archives/index.astro

Fix the archive page sorting.
Sort the archive page by `pubDatetime`.

fix: fix the archive page sorting

---

src/layouts/PostDetails.astro

The view transition animation of the "Post Title (h1, h2, h3...)" between the post list pages and the post pages is weird,
because of the width mismatch of titles among these pages.
Solution: 
Making the title in post page an inline-block, like what a title on list page is.
See slow motion video:
Currently:
https://github.com/user-attachments/assets/b44727e8-cac2-4eeb-9ffa-4fb9a1751965
After fix:
https://github.com/user-attachments/assets/e2601111-b3aa-4a01-8fa8-3efe65dfabf8
None
None

fix: Improved view transition animation for post titles

---

astro.config.ts

Currently if `SITE.showArchives == false`, we still include the `/archives` page into the XML sitemap, which causes an issue in Google Search Console.
Closes: #

Excluded /archives from sitemap if this feature is disabled

---

src/components/Tag.astro
src/layouts/PostDetails.astro
src/pages/tags/index.astro

This PR modifies tag display to show original tag names instead of slugified versions in the frontend. 
Currently, tags like `JavaScript` are being slugified to `java-script` in the display, which affects readability and professional appearance. This change will maintain the original tag names for better user experience.

feat: use the original tag name for display

---

src/utils/loadGoogleFont.ts

The font weight parameter was present but not being passed to the URL. This PR ensures it is included. 
No breaking changes.

fix: embed font weight param in URL

---

src/styles/typography.css

Horizontal overflow occurs when a code block in markdown table is too long. This PR prevents that by adding line breaks (`break-all`) in codes inside table.

fix: prevent overflow by adding line breaks in table codes

---

src/components/EditPost.astro
src/config.ts
src/content.config.ts
src/data/blog/adding-new-post.md
src/data/blog/how-to-configure-astropaper-theme.md
src/layouts/PostDetails.astro

Fixed broken editPost link. Removed the ability to update the editPost link inside each blog post for consistency.
The editPost button per blog post can still be hidden.
Closes: #464

fix: broken editPost link and update editPost logic 

---

src/layouts/Layout.astro

In dark mode, there's an initial light mode flash when the page is loaded for the first time. 
This issue is fixed by removing `async` from `toogle-theme.js` script tag.
https://github.com/user-attachments/assets/11494412-cc4a-4dd5-85c2-cca678aedd9c

fix: initial light mode flash in dark mode

---

CHANGELOG.md
package.json
src/pages/search.astro

Multiple search bars appear whenever Search nav link is clicked on `/search` page.
https://github.com/user-attachments/assets/8b98d3f0-6521-46ca-9696-149a1d0290d3
Closes: #465

fix: ensure only one search bar is displayed on nav link clicks

---

src/components/ShareLinks.astro
src/components/Socials.astro
src/constants.ts

Modifying the `Socials.astro` file, add type definitions and conditional rendering to prevent type errors when `SOCIALS` is empty.
This modification resolves the TypeScript error when the `SOCIALS` array is empty by adding type definitions and using type assertions. When the array is empty, the map function does not execute, so no social icons are attempted to be rendered. This approach maintains the integrity of the original logic while simply adding type safety measures.
Closes: #500

fix: add types for constants to avoid type errors when empty

---

.github/workflows/ci.yml
package.json

Specify a specific packageManager version in package.json, to fix the issue while deploying in cloudflare
Add packageManager to fix the build break in CloudFlare while deploying
Closes: #

build: specify pnpm version in `package.json` and `ci.yml`

---

src/components/BackToTopButton.astro
src/layouts/PostDetails.astro

Make the back-to-top button appear based on scroll position_ improving accessibility and UX.
| Desktop | Mobile |
| -- | -- |
| <video src="https://github.com/user-attachments/assets/ab3dd0ee-027a-4c04-9198-a6eb8fa1ed94"> | <video src="https://github.com/user-attachments/assets/8d826043-bc41-4cf2-9080-79b80f4beff6">  |

feat: improve back-to-top button behavior

---

astro.config.ts
src/layouts/Layout.astro

use astro's new typesafe env - https://docs.astro.build/en/guides/environment-variables/
Closes: #

refactor: use new astro env

---

src/styles/global.css

Add few pixels of extra space on top of anchors for easier reading experience. 
> Before
> After
'ex' css unit is the line height of small `x` character so extra space is 5 times heights of small x
Closes: #

feat: scroll margin

---

src/components/BackButton.astro
src/components/Breadcrumb.astro
src/components/Header.astro
src/components/Hr.astro
src/data/blog/how-to-configure-astropaper-theme.md
src/layouts/AboutLayout.astro
src/layouts/Main.astro
src/layouts/PostDetails.astro
src/pages/404.astro
src/styles/global.css

Extract redundant max-width into a universal tailwind utility class. By doing so, the width of the layout in different pages can be customized easily.
https://github.com/user-attachments/assets/c6a145a0-736e-4e02-9ae7-bc7f41398dac
Obviously, there's a problem with BackToTop button.
Currently, we have to update the position property inside the `BackToTop` button when we update the `max-w-app`.
There's gonna be a PR for that.
#490 #436

refactor: extract redundant max-width into utility

---

src/data/blog/customizing-astropaper-theme-color-schemes.md

While working with AstroPaper I noticed the docs for customizing color schemes were outdated.
Tried my best to update the docs for this, not sure about the detail explanation though, because I haven't customized the theme myself yet :)
Closes: #

docs: update customize-color-schemes doc to match current files

---

src/layouts/PostDetails.astro

There was no option to click the heading anchors on mobile because their visibility was based on hover.
https://github.com/user-attachments/assets/010c13ca-2b06-4665-adfd-a0437ef1c83d

fix: make heading anchors in article visible on mobile

---

astro.config.ts
src/layouts/PostDetails.astro
src/styles/global.css
src/utils/transformers/fileName.js

- Add v2 badge-style option as alternative to v1 tab-style
- v2 features: border, rounded corners, positioned with CSS custom property
- v1 features: tab-style with rounded top corners, muted background
- Add hideDot option to control green dot indicator visibility
- Include comprehensive JSDoc documentation with usage examples
- Support both styling variants with configuration parameters
| v1 | v2 |
| -- | -- |
| ![image](https://github.com/user-attachments/assets/d1021801-26a9-4329-8fa1-a0d38467844f) | ![image](https://github.com/user-attachments/assets/177ccf44-b3f4-4df7-9568-c1fc10a565c2) |
**V1**
```ts
export default defineConfig({
// ...
markdown: {
// ...
shikiConfig: {
// ...
transformers: [
transformerFileName({ style: "v1", hideDot: false }),
transformerNotationHighlight(), …
```

feat: enhance file name transformer with additional options

---

src/styles/typography.css

Improve syntax highlighting transformer styles.
| Before | After |
| --- | --- |
| <img width="1804" height="1764" alt="before-update" src="https://github.com/user-attachments/assets/894e244b-c522-4bf9-b4d8-7741b913eddb" /> | <img width="1804" height="1764" alt="after-update" src="https://github.com/user-attachments/assets/28053844-9877-4a6f-b6e9-beef89c020da" /> |

fix: update syntax highlighting transformer styles

---

package.json
pnpm-lock.yaml

- Updated astro from 5.11.0 to 5.12.0 in package.json and pnpm-lock.yaml.
- Upgraded @astrojs/markdown-remark from 6.3.2 to 6.3.3.
- Updated smol-toml from 1.3.1 to 1.4.1.
- Updated semver from 7.7.1 to 7.7.2.

bump: update astro to version 5.12.0 and related dependencies
